name: first workflow

on: push

jobs:
  first-workflow-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: install dependency
        run: npm install

      - name: test ESLint
        run: npm test -- --watchAll=false

      - name : run ESlint
        run: npm run lint

      - name: make react build
        run: npm run build